### ISSUE TITLE
Clarification of which license applies to what

### ISSUE THREAD

**Issue by ghisvail** [rjw57/dtcwt#109]
Could you break down what in the source tree is under the BSD-2-Clause license and what is subject to the custom free-but-restricive license ? I thought this toolbox could be a great fit for packaging in our Debian science team, but the free-but-restricive stuff would need to be curated from the release tarball, assuming the remaining modules can run without.

Cheers,

**Comment by rjw57** [comment]
All Python code in this repository is BSD 2-clause licensed.

The original implementation of the DTCWT includes this clause:
```
In return for supplying the code, all I ask is that, if
you use the algorithms, you give due reference to this work in any
papers that you write and that you let me know if you find any good
applications for the DT CWT.
```
Note that the original license uses the language "use the algorithms" which is unclear. The code in this repo implements the DT-CWT algorithm and if an *algorithm* is covered by copyright in a given area, any use requires referencing. If algorithms are not copyright-able then use does not. I have no control over this and I don't want to try to interpret the original license.

So, all code in this repository is under the BSD-2-clause license but has been written to be similar to the original MATLAB toolbox API and uses the DT-CWT algorithm. You need to determine for yourself if the original algorithm and API can be copyrighted and, if so, if the referencing requirement applies and, if so, if it is DFSG-friendly.

An easier approach may be to contact the original author (see ``ORIGINAL_README.txt``) and ask them to clarify whether they mean "algorithm" or "code" in their original license.

I believe that the software is DFSG-friendly if an algorithm cannot in itself be copyrighted.

**Comment by rjw57** [comment]
Closing since I've answered to the best of my ability but feel free to re-open if you want to discuss further.
