### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by fedorov** [rjw57/dtcwt#121]
The statement "License: Free To Use But Restricted" is confusing. Please include the actual license, which is a standard practice for open source development.

**Comment by rjw57** [comment]
The actual license is in the [COPYING.txt](https://github.com/rjw57/dtcwt/blob/master/COPYING.txt) file, as is standard practice for open source development. It has been there for 2 years. HTH.

**Comment by rjw57** [comment]
This issue made me take a look at the file and chop out an unneeded bit, though, so thanks for raising.
