### ISSUE TITLE
Availability of fully orthogonal DTCWT transform

### ISSUE THREAD

**Issue by gnthibault** [rjw57/dtcwt#131]
Hello all,

First, I would like to thank you for the work you did by providing this implementation of the DTCWT.

By reading the papers from Nick Kingsbury, and Ivan Selesnick, what I understood is that both worked on orthogonal/bi-orthogonal version of the DTCWT, and that, in the tutorial paper from 2005, they explained why biorthogonal filtering at first stage and Q-Shift filter at other stages provided the best tradeof regarding HIlbert transform approximation hence directional sensitivity and vanishing moments, spatial/temporal selectivity.

However, in the framework of convex optimization, fully orthogonal decomposition are more interesting, in the sense that many algorithm simplifies in this case. I wanted to try that, but, when I look at the documentation : https://dtcwt.readthedocs.io/en/0.11.0/reference.html#dtcwt.coeffs.biort

It doesn't look like a fully orthogonal docomposition is available. Is the support for fully orthogonal decomposition likely to be supported in the near future ? or is the fully orthogonal solution far less efficient that any of the bi-orth/q-shift version ?

Thank you in advance for your help

**Comment by rjw57** [comment]
Hi, thanks for your kind words.

There are no plans to implement other variants of the transform at the moment but pull requests adding functionality are always welcome if they come with good tests and documentation.
