### ISSUE TITLE
Fauqueur method in find_keypoints

### ISSUE THREAD

**Issue by nicolezk1** [rjw57/dtcwt#133]
I was wondering why in the function 
```
def _keypoint_energy_fauqueur(subband, alpha, beta):
    return alpha * np.power(np.maximum(0, np.product(np.abs(subband), axis=2)), beta)
```
The alpha is not powered by the scale/level number, as it is described in [1] (in equation 1).

[1] Julien Fauqueur, Nick Kingsbury, and Ryan Anderson. *Multiscale
    Keypoint Detection using the Dual-Tree Complex Wavelet Transform*. 2006
    International Conference on Image Processing, pages 1625-1628, October
    2006. ISSN 1522-4880. doi: 10.1109/ICIP.2006.312656.
    http://ieeexplore.ieee.org/lpdocs/epic03/wrapper.htm?arnumber=4106857.

**Comment by rjw57** [comment]
Most likely it's a transcription bug. Feel free to open a PR and I'll accept.

**Comment by rjw57** [comment]
Thanks for spotting it, BTW.
