### ISSUE TITLE
How to obtain lowpass coefficients at each level of the transform

### ISSUE THREAD

**Issue by WEIAI-TECH** [rjw57/dtcwt#141]
How can I  obtain lowpass coefficients at each level of the transform as Matlab does: [a,d,**as**] = dualtree(wecg,'Level',4). Thanks

**Comment by WEIAI-TECH** [comment]
The problem was solved.

**Comment by Donxupengzhi** [comment]
Dear Professor Wei,
        Could you please tell me how do you solve this problem?

**Comment by shoukewei** [comment]
Hi there，I am travelling for a business. You can visit my blog and search wavelet, and then you will find detailed articles about your question.All the bestShouke Wei, PhDSent from my iPhoneOn May 13, 2023, at 11:10 AM, Donxupengzhi ***@***.***> wrote:﻿
Dear Professor Wei,
Could you please tell me how do you solve this problem?

**Comment by Donxupengzhi** [comment]
Dear Professor,
        Thank you for your reply！I have visited your blog but I just found articles about DWT rather than DTCWT. I am wondering if I missed something.
        Wishing you all the best.
